### PR TITLE
W03 d03 dawn express intro

### PR DESCRIPTION
**Pull request by tgaff**
**please also see** https://github.com/sf-wdi-25/express-intro

### CODE REVIEW

**Comment by nathanallen** [comment]
Important to keep a clear distinction between public vs. server files to avoid confusing students. Here's the structure I'd recommend:

```
├── server.js  // let's avoid `app.js`
├── package.json
├── public  // i.e. client-side
│   ├── images
│   ├── javascripts
│       └── app.js
│   └── stylesheets
│       └── style.css
│   └── vendor // e.g. bower_components
└── views
│   ├── index.html
```

**Comment by nathanallen** [comment]
Might be interesting to combine $.ajax with method chaining:

``` js
$.ajax({
           method: 'GET',
           url: 'http://localhost:3000/api/albums'
  })
 .success(function(data){
    console.log(data)
  })
 .error(function(){
    console.log('uh oh')
  });
```
(I note jQuery does this in their ajax documentation).

Either way, probably want to avoid using `e` for the error callback. I don't want them confusing it with the event-object.

**Comment by nathanallen** [comment]
Began making changes to lab here: https://github.com/sf-wdi-25/express-intro/pull/1

**Comment by tgaff** [comment]
If they try to access the server from chrome when loading a page from the file system CORS is an issue.  curl doesn't care though.

**Comment by tgaff** [comment]
In terms of chaining we should just do one or the other.  Which do you guys ( @justincastilla  and @nathanallen ) prefer?

**Comment by tgaff** [comment]
@nathanallen I added your file decoder-ring.  That's always a bit tricky for them.  I'll need to make an adjustment to move index.html into views.  I'm asking them to move the files into public and views.

**Comment by tgaff** [comment]
Also added file tree here: https://github.com/sf-wdi-25/express-intro/pull/2  That helped tied things together better over there.

**Comment by nathanallen** [comment]
The more I think about the switch to `$.ajax` the more I like it:
- explicitly named key value pairs is huge (and it will drill them on what a "method" is)
- argument order doesn't matter (meaning optional arguments make more sense)

**Pull request merged**
