### PR TITLE
break homework setup

### LINKED ISSUE #43: Holiday break reading/assignments
@justincastilla @nathanallen @HeyStenson 

Please add ideas, suggestions for holiday assignments.

### PR DESCRIPTION
**Pull request by nathanallen**
closes #43

### CODE REVIEW

**Comment by nathanallen** [comment]
@tgaff please add reading / ruby prep
@justincastilla  please add ruby method instructions

**Comment by tgaff** [comment]
@nathanallen I thought we decided to have them resolve two issues on their project 1 as a homework assignment.

**Comment by nathanallen** [comment]
@tgaff thanks, added 39c75ba

**Comment by tgaff** [comment]
That should keep them busy :-/

**Pull request merged**
